In [2]:
import cv2
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.utils import to_categorical

In [3]:
import os
print(os.getcwd())
data_path="clothing-dataset/images.csv"
image_path="clothing-dataset/images/"

c:\Users\ishus\OneDrive\Desktop\project


In [4]:
df = pd.read_csv(data_path)
print(df.head())
X = []
y = []
error=[]
for i in range(len(df)):
    path=image_path+df['image'][i]+".jpg"
    # print(path)
    img = cv2.imread(path)
    # print(img)
    if img is None :
        print(path)
        error.append(i)
        continue
    img = cv2.resize(img, (100, 100))
    X.append(img)
    y.append(df['label'][i])
    
X = np.array(X)
X = X / 255.0
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = to_categorical(y)

                                  image  sender_id     label   kids
0  4285fab0-751a-4b74-8e9b-43af05deee22        124  Not sure  False
1  ea7b6656-3f84-4eb3-9099-23e623fc1018        148   T-Shirt  False
2  00627a3f-0477-401c-95eb-92642cbe078d         94  Not sure  False
3  ea2ffd4d-9b25-4ca8-9dc2-bd27f1cc59fa         43   T-Shirt  False
4  3b86d877-2b9e-4c8b-a6a2-1d87513309d0        189     Shoes  False
clothing-dataset/images/d028580f-9a98-4fb5-a6c9-5dc362ad3f09.jpg
clothing-dataset/images/1d0129a1-f29a-4a3f-b103-f651176183eb.jpg
clothing-dataset/images/784d67d4-b95e-4abb-baf7-8024f18dc3c8.jpg
clothing-dataset/images/c60e486d-10ed-4f64-abab-5bb698c736dd.jpg
clothing-dataset/images/040d73b7-21b5-4cf2-84fc-e1a80231b202.jpg


In [5]:
print(error)
print(X.shape)
print(y.shape)
print(X[0])
print(y[0])

[533, 703, 861, 1662, 1763]
(5398, 100, 100, 3)
(5398, 20)
[[[0.35686275 0.61568627 0.58431373]
  [0.31372549 0.59215686 0.54117647]
  [0.29019608 0.58039216 0.49803922]
  ...
  [0.45882353 0.6627451  0.63137255]
  [0.4627451  0.6745098  0.63921569]
  [0.42745098 0.65098039 0.61568627]]

 [[0.36862745 0.62352941 0.58431373]
  [0.29411765 0.58431373 0.53333333]
  [0.30196078 0.60784314 0.54117647]
  ...
  [0.46666667 0.67058824 0.63921569]
  [0.45490196 0.66666667 0.63137255]
  [0.41568627 0.63921569 0.60392157]]

 [[0.36470588 0.60784314 0.56862745]
  [0.3254902  0.61960784 0.57254902]
  [0.30196078 0.61960784 0.57647059]
  ...
  [0.47843137 0.68235294 0.64705882]
  [0.44705882 0.65882353 0.62352941]
  [0.41568627 0.63921569 0.60392157]]

 ...

 [[0.30980392 0.50980392 0.49411765]
  [0.30196078 0.51372549 0.48627451]
  [0.2745098  0.50196078 0.45882353]
  ...
  [0.4627451  0.68627451 0.65490196]
  [0.45882353 0.68235294 0.65490196]
  [0.44705882 0.67058824 0.63921569]]

 [[0.28235294 0

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Create a convolutional neural network model:

This CNN model is intended for image classification and consists of two convolutional layers followed by max-pooling layers, a fully connected (dense) layer, and an output layer with a softmax activation function for multi-class classification.

Here’s a breakdown of the model:

Conv2D Layer (32 filters, 3x3 kernel size, ReLU activation):

The first convolutional layer extracts features from the input image, where input_shape=(100, 100, 3) specifies the input size (100x100 RGB image).
MaxPooling2D Layer (2x2 pool size):

The max-pooling layer reduces the spatial dimensions (height and width) of the feature maps by selecting the maximum value in each 2x2 region.
Conv2D Layer (64 filters, 3x3 kernel size, ReLU activation):

The second convolutional layer extracts higher-level features with a larger number of filters (64 filters).
MaxPooling2D Layer (2x2 pool size):

Another max-pooling layer to reduce the spatial dimensions of the feature maps.
Flatten Layer:

This layer flattens the multi-dimensional input (the feature maps) into a 1D vector, which can then be fed into fully connected layers.
Dense Layer (128 units, ReLU activation):

A fully connected layer with 128 neurons, using the ReLU activation function to introduce non-linearity.
Dense Output Layer (5 units, softmax activation):

The output layer has 5 neurons (for 5 classes), and softmax is used as the activation function to produce class probabilities.
Compilation:

Loss: categorical_crossentropy is used, which is appropriate for multi-class classification problems where each class is mutually exclusive.
Optimizer: adam, an adaptive learning rate optimization algorithm that works well for many tasks.
Metrics: You are using accuracy to evaluate the model's performance during training and evaluation.

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Initialize the Sequential model
model = Sequential()

# First convolutional layer: 32 filters, 3x3 kernel, ReLU activation, input shape for 100x100 RGB images
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(100, 100, 3)))

# Max-pooling layer to reduce spatial dimensions
model.add(MaxPooling2D(pool_size=(2, 2)))

# Second convolutional layer: 64 filters, 3x3 kernel, ReLU activation
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))

# Max-pooling layer to reduce spatial dimensions
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten the feature maps to a 1D vector
model.add(Flatten())

# Fully connected layer with 128 neurons and ReLU activation
model.add(Dense(128, activation='relu'))

# Output layer: 5 neurons (for 5 classes) with softmax activation
model.add(Dense(20, activation='softmax'))

# Compile the model with categorical crossentropy loss, adam optimizer, and accuracy metric
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Model summary (optional, to check the model architecture)
#model.summary()



c:\Users\ishus\OneDrive\Desktop\project\venv\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Train the model on the training data:

In [8]:
model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 11s 66ms/step - accuracy: 0.2530 - loss: 2.5571 - val_accuracy: 0.4546 - val_loss: 1.9773
Epoch 2/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 8s 62ms/step - accuracy: 0.4948 - loss: 1.7441 - val_accuracy: 0.5306 - val_loss: 1.6628
Epoch 3/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 10s 77ms/step - accuracy: 0.6523 - loss: 1.1898 - val_accuracy: 0.5454 - val_loss: 1.6931
Epoch 4/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 14s 100ms/step - accuracy: 0.7626 - loss: 0.7855 - val_accuracy: 0.5463 - val_loss: 1.7359
Epoch 5/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 10s 71ms/step - accuracy: 0.8591 - loss: 0.4789 - val_accuracy: 0.5509 - val_loss: 2.0469
Epoch 6/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 11s 79ms/step - accuracy: 0.9408 - loss: 0.2377 - val_accuracy: 0.5380 - val_loss: 2.1828
Epoch 7/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 10s 77ms/step - accuracy: 0.9765 - loss: 0.1258 - val_accuracy: 0.5398 - val_loss: 2.6282
Epoch 8/10
135/135 ━━━━━━━━━━━━━━━━━━━━ 11s 83ms/step - accuracy: 0.9914 - loss: 0.0550 - 

Load the user’s wardrobe images and predict the clothing labels:

In [15]:
wardrobe = []


while True:
    img_path = input("Enter image path: ")
    if img_path == "":
        break
    img = cv2.imread(img_path)
    img = cv2.resize(img, (100, 100))
    img = img / 255.0
    wardrobe.append(img)
wardrobe = np.array(wardrobe)
labels = model.predict(wardrobe)
labels = label_encoder.inverse_transform(labels)

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


Ask the user for their preferences and occasion:

In [16]:

occasion = input("Enter occasion: ")
preferences = []
while True:
    preference = input("Enter preference (type 'done' when finished): ")
    if preference == "done":
        break
    preferences.append(preference)

Recommend outfit combinations based on the user’s preferences and the occasion:

In [19]:
df_outfits = pd.read_csv("images.csv")
outfits = df_outfits.loc[(df_outfits['occasion'] == occasion) & df_outfits['top'].isin(preferences) & df_outfits['bottom'].isin(preferences) & df_outfits['shoes'].isin(preferences)]
outfit_labels = []
for i in range(len(outfits)):
    outfit = outfits.iloc[i]
    top_label = labels[np.where(label_encoder.classes_ == outfit['top'])[0][0]]
    bottom_label = labels[np.where(label_encoder.classes_ == outfit['bottom'])[0][0]]
    shoes_label = labels[np.where(label_encoder.classes_ == outfit['shoes'])[0][0]]
    outfit_label = f"{top_label} + {bottom_label} + {shoes_label}"
    outfit_labels.append(outfit_label)
if len(outfit_labels) == 0:
    print("Sorry, we couldn't find any matching outfits.")
else:
    print("Here are some outfit suggestions for you:")
    for outfit_label in outfit_labels:
        print(outfit_label)

FileNotFoundError: [Errno 2] No such file or directory: 'images.csv'